### ISSUE TITLE
Extension deployed to non-AKS cluster doesn't configure "nvidia.com/gpu"

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#174]
Hi.
After deploying the extension to a non-AKS cluster, we tried (and failed) to get a training job deployed to the node.

We had created the defaultinstancetype as below:
```yaml
---
apiVersion: amlarc.azureml.com/v1alpha1
kind: InstanceType
metadata:
    name: defaultinstancetype
spec:
    nodeSelector:
        nodepool: "np-12-gpu"
    resources:
        limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
```

However, the node doesn't have `nvidia.com/gpu` listed in the node capacity:
```yaml
status:
  capacity:
    cpu: '18'
    ephemeral-storage: 812818308Ki
    github.com/fuse: 1k
    hugepages-1Gi: '0'
    hugepages-2Mi: '0'
    memory: 90625620Ki
    pods: '110'
  allocatable:
    cpu: 17760m
    ephemeral-storage: 782539652Ki
    github.com/fuse: 1k
    hugepages-1Gi: '0'
    hugepages-2Mi: '0'
    memory: 84789844Ki
    pods: '110'
```

Is this supposed to be configured by install triggered by "installNvidiaDevicePlugin: True"?
Or was this supposed to be already in the node from the original kubernetes install?
(tagging @Bozhong68)
Thanks
