### ISSUE TITLE
"az ml online-deployment update" doesn't update instance_type from yaml file

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#247]
Hi,
We are trying to change the instance_type of an existing online-endpoint deployment from "defaultinstancetype" to something else (already created).

We updated the yaml file that was used to create the endpoint originally to point to the new instance_type
```yaml
---
$schema: https://azuremlschemas.azureedge.net/latest/kubernetesOnlineDeployment.schema.json

endpoint_name: ENDPOINT_NAME_00
type: kubernetes
name: DEPLOYMENT_NAME_00

instance_type: NEW_INST_TYPE_00
# instance_type: defaultinstancetype
instance_count: 1
...
```

Command executed
`az ml online-deployment update -f ./azml.deployment.yml -o json --resource-group RGNAME --subscription SUBS_ID --workspace-name WS_NAME` 

Any alternative besides the following?
* remove/redeploy endpoint+deployment
* deploy new deployment, move traffic there, to then remove previous deployment?

We were not able to finds anything in the documentation mentioning that instance_types cannot be created.
If argument is ignored, prob would be safer to either abort update or, at least, provide a warning (even if in verbose mode).

Thanks
