### ISSUE TITLE
"Cannot override existing endpoint: InferenceLiveness" error when customizing "inference_config.*.path"

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#251]
Hi,
We are trying to configure BYOC inference, as per https://github.com/Azure/AML-Kubernetes/blob/master/docs/inference-byoc.md#create-the-deployment.

## deployment
```yaml
environment:
  inference_config:
    liveness_route:
      port: 5001
      path: /
    readiness_route:
      port: 5001
      path: /
    scoring_route:
      port: 5001
      path: /score
```

Even when creating a new endpoint and a new deployment, we get the following error message
```
az ml online-deployment create -f ./my-byoc-deployment.yml --all-traffic -o json --resource-group MY_RG --subscription MY_SUBS_ID --workspace-name MY_AML_WS
All traffic will be set to deployment netcore-embed-1 once it has been provisioned.
If you interrupt this command or it times out while waiting for the provisioning, you can try to set all the traffic to this deployment later once its has been provisioned.
Check: endpoint MY_EP_NAME exists
(ValidationError) Cannot override existing endpoint: InferenceLiveness
Code: ValidationError
Message: Cannot override existing endpoint: InferenceLiveness
Exception Details:      (Invalid) Cannot override existing endpoint: InferenceLiveness
        Code: Invalid
        Message: Cannot override existing endpoint: InferenceLiveness
        Target: EnvironmentDefinition
Additional Information:Type: ComponentName
Info: {
    "value": "managementfrontend"
}Type: Correlation
Info: {
    "value": {
        "operation": "d7b2590abc52964b9c419daae732d145",
        "request": "24c44227a1dc42f3"
    }
}Type: Environment
Info: {
    "value": "westeurope"
}Type: Location
Info: {
    "value": "westeurope"
}Type: Time
Info: {
    "value": "2022-07-12T21:04:43.4605579+00:00"
}
```

Any ideas on where to find a documentation of restrictions related to this customization?
Thx
