### ISSUE TITLE
pending jobs in aks cluster

### ISSUE THREAD

**Issue by yazbekhe** [Azure/AML-Kubernetes#298]
when a job try to  run and there is no enough resources in the cluster the job fails directly without even trying to schedule the pod. it seems there is a pre-check. we need to put that the pod goes in pending to initiate cluster scale-out

**Comment by yuyue9284** [comment]
Hi @yazbekhe , please follow the steps in this doc: https://learn.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-kubernetes-extension?view=azureml-api-2#volcano-scheduler-integration-supporting-cluster-autoscaler and give a try.

**Comment by yuyue9284** [comment]
The example config needs to be updated with:
```yaml
volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: sla 
        arguments:
          sla-waiting-time: 1m
    - plugins:
      - name: conformance
    - plugins:
        - name: drf
        - name: predicates
        - name: proportion
        - name: nodeorder
        - name: binpack
```
